### ISSUE TITLE
[Follow the new guidance from hacktoberfest]

### ISSUE THREAD

**Issue by altafshaikh** [avats-dev/motivate#109]
PRs count if:
Submitted during the month of October AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by avats-dev** [comment]
@altafshaikh first check the repo before opening an issue, it has been already done.
